### ISSUE TITLE
Error when trying to run bash_scripts/osr_train_tinyimagenet.sh

### ISSUE THREAD

**Issue by NivC** [sgvaze/osr_closed_set_all_you_need#2]
Hi,

Thank you for publishing the code!

I tried to follow the instruction to first run your method as described.

I received the error trace below.

Your assistance would be greatly appreciated.

Niv.

---------------------------------------

6
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/methods/ARPL/osr.py", line 277, in <module>
    cifar_plus_n=args.out_num, args=args)
TypeError: get_class_splits() got an unexpected keyword argument 'args'
7
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/methods/ARPL/osr.py", line 277, in <module>
    cifar_plus_n=args.out_num, args=args)
TypeError: get_class_splits() got an unexpected keyword argument 'args'
8
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/methods/ARPL/osr.py", line 277, in <module>
    cifar_plus_n=args.out_num, args=args)
TypeError: get_class_splits() got an unexpected keyword argument 'args'
9
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/methods/ARPL/osr.py", line 277, in <module>
    cifar_plus_n=args.out_num, args=args)
TypeError: get_class_splits() got an unexpected keyword argument 'args'
10
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cs/labs/peleg/nivc/multimodal_ad/osr_closed_set_all_you_need/methods/ARPL/osr.py", line 277, in <module>
    cifar_plus_n=args.out_num, args=args)
TypeError: get_class_splits() got an unexpected keyword argument 'args'

**Comment by sgvaze** [comment]
Hello, thanks for pointing this out! It was a minor incompatibility caused by the code cleaning. The latest commit should fix it!  75a0694abdd4ca8e37695b507d52cb04a2cb9fa7
